import type { Supplier } from "@/lib/types";

export const mockSuppliers: Supplier[] = [
  {
    id: "apex-tech",
    name: "ApexTech Enterprise Systems",
    contactName: "Rohit Shah",
    email: "rfq.apextech@example.com",
    region: "West India",
    leadTimeDays: 9,
    avgUnitPrice: 72500,
    warrantyYears: 3,
    complianceScore: 94,
    serviceScore: 91,
    sustainabilityScore: 84,
    stockUnits: 420,
    laptopLines: ["Business ultrabook", "Engineering workstation"],
    certifications: ["ISO 9001", "EPEAT partner", "MSME compliant"]
  },
  {
    id: "nova-digital",
    name: "Nova Digital Procurement",
    contactName: "Ananya Iyer",
    email: "enterprise.nova@example.com",
    region: "South India",
    leadTimeDays: 12,
    avgUnitPrice: 68400,
    warrantyYears: 3,
    complianceScore: 89,
    serviceScore: 87,
    sustainabilityScore: 78,
    stockUnits: 650,
    laptopLines: ["Business ultrabook", "Standard productivity"],
    certifications: ["ISO 27001", "OEM authorized reseller"]
  },
  {
    id: "vertex-supply",
    name: "Vertex Supply Chain Solutions",
    contactName: "Neha Kulkarni",
    email: "bids.vertex@example.com",
    region: "Pan India",
    leadTimeDays: 7,
    avgUnitPrice: 75800,
    warrantyYears: 4,
    complianceScore: 96,
    serviceScore: 94,
    sustainabilityScore: 91,
    stockUnits: 380,
    laptopLines: ["Engineering workstation", "Executive laptop"],
    certifications: ["ISO 14001", "EPEAT Gold portfolio", "OEM authorized reseller"]
  },
  {
    id: "precision-it",
    name: "Precision IT Commerce",
    contactName: "Karan Mehta",
    email: "corporate.precision@example.com",
    region: "North India",
    leadTimeDays: 15,
    avgUnitPrice: 64200,
    warrantyYears: 2,
    complianceScore: 82,
    serviceScore: 80,
    sustainabilityScore: 69,
    stockUnits: 900,
    laptopLines: ["Standard productivity", "Business ultrabook"],
    certifications: ["GST verified", "OEM registered partner"]
  },
  {
    id: "orbit-enterprise",
    name: "Orbit Enterprise Devices",
    contactName: "Priya Nair",
    email: "rfq.orbit@example.com",
    region: "West India",
    leadTimeDays: 10,
    avgUnitPrice: 70400,
    warrantyYears: 3,
    complianceScore: 91,
    serviceScore: 88,
    sustainabilityScore: 86,
    stockUnits: 520,
    laptopLines: ["Business ultrabook", "Rugged field laptop"],
    certifications: ["ISO 9001", "E-waste compliant"]
  }
];
